//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICT365_A1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICT365_A1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://www.w3.org/2001/12/soap-envelope&quot; SOAP-ENV:encodingStyle=&quot;http://www.w3.org/2001/12/soap-encoding&quot; &gt;
        ///  &lt;SOAP-ENV:Body xmlns:hse=&quot;http://projects.awgm.co/hindsightevents&quot; &gt;
        ///      &lt;hse:Event&gt;
        ///        &lt;hse:eventid&gt;1&lt;/hse:eventid&gt;
        ///        &lt;hse:location&gt;
        ///          &lt;hse:lat&gt;-32.21976036&lt;/hse:lat&gt;
        ///          &lt;hse:long&gt;115.79785824&lt;/hse:long&gt;
        ///        &lt;/hse:location&gt;
        ///        &lt;hse:datetimestamp&gt;01/Jan/2017 01:32:00&lt;/hse:datetimestamp&gt;
        ///        &lt;h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string hindsight_events {
            get {
                return ResourceManager.GetString("hindsight_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://www.w3.org/2001/12/soap-envelope&quot; SOAP-ENV:encodingStyle=&quot;http://www.w3.org/2001/12/soap-encoding&quot; &gt;
        ///  &lt;SOAP-ENV:Body xmlns:hsp=&quot;http://projects.awgm.co/hindsightpeople&quot; &gt;
        ///    &lt;hsp:Person&gt;
        ///      &lt;hsp:name&gt;
        ///        &lt;hsp:fname&gt;Andrew&lt;/hsp:fname&gt;
        ///        &lt;hsp:lname&gt;Graham&lt;/hsp:lname&gt;
        ///      &lt;/hsp:name&gt;
        ///      &lt;hsp:phone&gt;0426198879&lt;/hsp:phone&gt;
        ///      &lt;hsp:address&gt;
        ///        &lt;hsp:streetNo&gt;8&lt;/hsp:streetNo&gt;
        ///        &lt;hsp:street&gt;C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string hindsight_people {
            get {
                return ResourceManager.GetString("hindsight_people", resourceCulture);
            }
        }
    }
}
